// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// th_vertical
List th_vertical(arma::vec xtime, arma::vec Delta, arma::vec D1, arma::vec D2, arma::mat X, arma::mat Z, arma::mat Bt, arma::vec W, arma::mat Q, arma::vec ibeta, arma::vec igamma1, arma::vec igamma2, arma::vec ikappa1, arma::vec ikappa2, arma::vec iU, arma::vec izetah, arma::vec izetal, arma::vec irho, double h1, double h2, double itheta, double lr, int mite, int miter, double eps);
RcppExport SEXP _VerticalCR_th_vertical(SEXP xtimeSEXP, SEXP DeltaSEXP, SEXP D1SEXP, SEXP D2SEXP, SEXP XSEXP, SEXP ZSEXP, SEXP BtSEXP, SEXP WSEXP, SEXP QSEXP, SEXP ibetaSEXP, SEXP igamma1SEXP, SEXP igamma2SEXP, SEXP ikappa1SEXP, SEXP ikappa2SEXP, SEXP iUSEXP, SEXP izetahSEXP, SEXP izetalSEXP, SEXP irhoSEXP, SEXP h1SEXP, SEXP h2SEXP, SEXP ithetaSEXP, SEXP lrSEXP, SEXP miteSEXP, SEXP miterSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type xtime(xtimeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type D1(D1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type D2(D2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Bt(BtSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ibeta(ibetaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type igamma1(igamma1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type igamma2(igamma2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ikappa1(ikappa1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ikappa2(ikappa2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type iU(iUSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type izetah(izetahSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type izetal(izetalSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type irho(irhoSEXP);
    Rcpp::traits::input_parameter< double >::type h1(h1SEXP);
    Rcpp::traits::input_parameter< double >::type h2(h2SEXP);
    Rcpp::traits::input_parameter< double >::type itheta(ithetaSEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< int >::type mite(miteSEXP);
    Rcpp::traits::input_parameter< int >::type miter(miterSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(th_vertical(xtime, Delta, D1, D2, X, Z, Bt, W, Q, ibeta, igamma1, igamma2, ikappa1, ikappa2, iU, izetah, izetal, irho, h1, h2, itheta, lr, mite, miter, eps));
    return rcpp_result_gen;
END_RCPP
}
// tw_updateb
List tw_updateb(arma::vec xtime, arma::vec Delta, arma::mat X, arma::mat Q, arma::vec ibeta, arma::vec iu, arma::vec izetah, arma::vec phih, arma::vec phih2, double lr);
RcppExport SEXP _VerticalCR_tw_updateb(SEXP xtimeSEXP, SEXP DeltaSEXP, SEXP XSEXP, SEXP QSEXP, SEXP ibetaSEXP, SEXP iuSEXP, SEXP izetahSEXP, SEXP phihSEXP, SEXP phih2SEXP, SEXP lrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type xtime(xtimeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ibeta(ibetaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type iu(iuSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type izetah(izetahSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phih(phihSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phih2(phih2SEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    rcpp_result_gen = Rcpp::wrap(tw_updateb(xtime, Delta, X, Q, ibeta, iu, izetah, phih, phih2, lr));
    return rcpp_result_gen;
END_RCPP
}
// tw_updateg
List tw_updateg(arma::vec Delta, arma::vec D, arma::mat Q, arma::mat ZB, arma::vec iu, arma::vec igammak, arma::vec phil, arma::vec izetal, arma::vec irho, double zeta_lr_pi, double lr);
RcppExport SEXP _VerticalCR_tw_updateg(SEXP DeltaSEXP, SEXP DSEXP, SEXP QSEXP, SEXP ZBSEXP, SEXP iuSEXP, SEXP igammakSEXP, SEXP philSEXP, SEXP izetalSEXP, SEXP irhoSEXP, SEXP zeta_lr_piSEXP, SEXP lrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ZB(ZBSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type iu(iuSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type igammak(igammakSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phil(philSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type izetal(izetalSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type irho(irhoSEXP);
    Rcpp::traits::input_parameter< double >::type zeta_lr_pi(zeta_lr_piSEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    rcpp_result_gen = Rcpp::wrap(tw_updateg(Delta, D, Q, ZB, iu, igammak, phil, izetal, irho, zeta_lr_pi, lr));
    return rcpp_result_gen;
END_RCPP
}
// tw_updateu
List tw_updateu(arma::vec xtime, arma::vec Delta, arma::vec D, arma::mat X, arma::mat Q, arma::mat ZB, arma::vec ibeta, arma::vec iu, arma::vec igammak, arma::vec irho, double itheta, double lr);
RcppExport SEXP _VerticalCR_tw_updateu(SEXP xtimeSEXP, SEXP DeltaSEXP, SEXP DSEXP, SEXP XSEXP, SEXP QSEXP, SEXP ZBSEXP, SEXP ibetaSEXP, SEXP iuSEXP, SEXP igammakSEXP, SEXP irhoSEXP, SEXP ithetaSEXP, SEXP lrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type xtime(xtimeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ZB(ZBSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ibeta(ibetaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type iu(iuSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type igammak(igammakSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type irho(irhoSEXP);
    Rcpp::traits::input_parameter< double >::type itheta(ithetaSEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    rcpp_result_gen = Rcpp::wrap(tw_updateu(xtime, Delta, D, X, Q, ZB, ibeta, iu, igammak, irho, itheta, lr));
    return rcpp_result_gen;
END_RCPP
}
// tw_verticalite2
List tw_verticalite2(arma::vec Delta, arma::vec D, arma::vec ZBg, arma::vec qu, arma::vec irho, double lr, int mite, double eps, double rho_bound);
RcppExport SEXP _VerticalCR_tw_verticalite2(SEXP DeltaSEXP, SEXP DSEXP, SEXP ZBgSEXP, SEXP quSEXP, SEXP irhoSEXP, SEXP lrSEXP, SEXP miteSEXP, SEXP epsSEXP, SEXP rho_boundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ZBg(ZBgSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type qu(quSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type irho(irhoSEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< int >::type mite(miteSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< double >::type rho_bound(rho_boundSEXP);
    rcpp_result_gen = Rcpp::wrap(tw_verticalite2(Delta, D, ZBg, qu, irho, lr, mite, eps, rho_bound));
    return rcpp_result_gen;
END_RCPP
}
// tw_verticalite3
List tw_verticalite3(arma::vec xtime, arma::vec Delta, arma::vec D, arma::mat X, arma::mat ZB, arma::vec qu, arma::mat Q, arma::vec ibeta, arma::vec iU, arma::vec igammak, arma::vec phih, arma::vec phih2, arma::vec phil, arma::vec phil2, arma::mat ZBz, arma::vec irho, double itheta);
RcppExport SEXP _VerticalCR_tw_verticalite3(SEXP xtimeSEXP, SEXP DeltaSEXP, SEXP DSEXP, SEXP XSEXP, SEXP ZBSEXP, SEXP quSEXP, SEXP QSEXP, SEXP ibetaSEXP, SEXP iUSEXP, SEXP igammakSEXP, SEXP phihSEXP, SEXP phih2SEXP, SEXP philSEXP, SEXP phil2SEXP, SEXP ZBzSEXP, SEXP irhoSEXP, SEXP ithetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type xtime(xtimeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ZB(ZBSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type qu(quSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ibeta(ibetaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type iU(iUSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type igammak(igammakSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phih(phihSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phih2(phih2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phil(philSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phil2(phil2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ZBz(ZBzSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type irho(irhoSEXP);
    Rcpp::traits::input_parameter< double >::type itheta(ithetaSEXP);
    rcpp_result_gen = Rcpp::wrap(tw_verticalite3(xtime, Delta, D, X, ZB, qu, Q, ibeta, iU, igammak, phih, phih2, phil, phil2, ZBz, irho, itheta));
    return rcpp_result_gen;
END_RCPP
}
// tw_vertical
List tw_vertical(arma::vec xtime, arma::vec Delta, arma::vec D, arma::mat X, arma::mat Z, arma::mat Bt, arma::vec W, arma::mat Q, arma::vec ibeta, arma::vec igamma, arma::vec ikappa, arma::vec iU, arma::vec izetah, arma::vec izetal, arma::vec irho, double h1, double h2, double itheta, double lr, int mite, int miter, double eps, double rho_bound, double zeta_lr_pi);
RcppExport SEXP _VerticalCR_tw_vertical(SEXP xtimeSEXP, SEXP DeltaSEXP, SEXP DSEXP, SEXP XSEXP, SEXP ZSEXP, SEXP BtSEXP, SEXP WSEXP, SEXP QSEXP, SEXP ibetaSEXP, SEXP igammaSEXP, SEXP ikappaSEXP, SEXP iUSEXP, SEXP izetahSEXP, SEXP izetalSEXP, SEXP irhoSEXP, SEXP h1SEXP, SEXP h2SEXP, SEXP ithetaSEXP, SEXP lrSEXP, SEXP miteSEXP, SEXP miterSEXP, SEXP epsSEXP, SEXP rho_boundSEXP, SEXP zeta_lr_piSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type xtime(xtimeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Bt(BtSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ibeta(ibetaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type igamma(igammaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ikappa(ikappaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type iU(iUSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type izetah(izetahSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type izetal(izetalSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type irho(irhoSEXP);
    Rcpp::traits::input_parameter< double >::type h1(h1SEXP);
    Rcpp::traits::input_parameter< double >::type h2(h2SEXP);
    Rcpp::traits::input_parameter< double >::type itheta(ithetaSEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< int >::type mite(miteSEXP);
    Rcpp::traits::input_parameter< int >::type miter(miterSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< double >::type rho_bound(rho_boundSEXP);
    Rcpp::traits::input_parameter< double >::type zeta_lr_pi(zeta_lr_piSEXP);
    rcpp_result_gen = Rcpp::wrap(tw_vertical(xtime, Delta, D, X, Z, Bt, W, Q, ibeta, igamma, ikappa, iU, izetah, izetal, irho, h1, h2, itheta, lr, mite, miter, eps, rho_bound, zeta_lr_pi));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_VerticalCR_th_vertical", (DL_FUNC) &_VerticalCR_th_vertical, 25},
    {"_VerticalCR_tw_updateb", (DL_FUNC) &_VerticalCR_tw_updateb, 10},
    {"_VerticalCR_tw_updateg", (DL_FUNC) &_VerticalCR_tw_updateg, 11},
    {"_VerticalCR_tw_updateu", (DL_FUNC) &_VerticalCR_tw_updateu, 12},
    {"_VerticalCR_tw_verticalite2", (DL_FUNC) &_VerticalCR_tw_verticalite2, 9},
    {"_VerticalCR_tw_verticalite3", (DL_FUNC) &_VerticalCR_tw_verticalite3, 17},
    {"_VerticalCR_tw_vertical", (DL_FUNC) &_VerticalCR_tw_vertical, 24},
    {NULL, NULL, 0}
};

RcppExport void R_init_VerticalCR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
